### ISSUE TITLE
Repeated builds and installs

### ISSUE THREAD

**Issue by ahamid** [jfqd/puppet-module-build#1]
Hi, I noticed (at least on Puppet 0.25.5), that build::install doesn't not skip building and installing if the target file already exists.  I had to add an unless clause to all the exec resources:

```
unless  => "$test -f $creates"
```

**Comment by jfqd** [comment]
Yes, saw this issue in the code on github. Just add this line to fix it.

Exec { unless => "$test -f $creates" }

**Comment by ahamid** [comment]
hi there are a couple of other tweaks in my fork (namely conditionally downloading and deleting build dir), but i didn't separate them from the (minor) redhat/centos changes.

https://github.com/incandescent/puppet-module-build/commits/master/

**Comment by jfqd** [comment]
You get it all by adding this line:

Exec { unless => "$test -f $creates" }

Fixed it in my repo.
