### ISSUE TITLE
resource not found

### ISSUE THREAD

**Issue by deric** [jfqd/puppet-module-build#2]
I have puppet 3.1, I tried to put the build function into `nodes.pp`, but the definition doesn't seem to exist.

<pre>
Puppet::Parser::AST::Resource failed with error ArgumentError: Invalid resource type build::install at /etc/puppet/manifests/nodes.pp:79
</pre>
 

I thought the definition is autoloaded, am I doing something wrong?. Thanks

**Comment by jfqd** [comment]
Have you tried to add 

  import 'build'

to site.pp?

**Comment by deric** [comment]
Sorry, mine fault. I had the module named "module-build", which was not auto required
