### ISSUE TITLE
Dependency on external puppet parser functions

### ISSUE THREAD

**Issue by pswheeler** [jfqd/puppet-module-build#4]
init.pp has dependency on basename and gsub, my puppet installation didn't have these by default.  I found these at 
https://github.com/puzzle/puppet-common
and created put these in the module's lib/parser directory (which worked).

Just to make this easier for others, either of the follwing should suffice:
1)  Adding a lib directory with the appropriate files (which aren't complicated)
2)  Pulling in a submodule
or
3)  Adding more detailed instructions.

**Comment by jfqd** [comment]
Thanks for the report, added a note about this dependency.
